name: PHP Dependency Installation and Display

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Set your preferred PHP version here
          extensions: mbstring, intl, bcmath # You can add other extensions if required
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip git apache2

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"
        #continue-on-error: false   # This will cause the step to fail if Composer installation fails

      - name: Install project dependencies
        run: |
          composer install --no-scripts --no-autoloader --prefer-dist --no-cache
        #continue-on-error: false  # This will stop the workflow if install fails

      - name: Generate optimized autoload files
        run: composer dump-autoload --optimize

      - name: Set permissions
        run: sudo chown -R www-data:www-data .

      - name: Enable Apache mod_rewrite
        run: sudo a2enmod rewrite

      - name: Start Apache (if needed)
        run: |
          sudo service apache2 start
          sudo apache2ctl configtest

      - name: Display Installed Dependencies
        run: |
          echo "Installed Composer dependencies:"
          composer show
