name: PHP Dependency Installation and Display

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Set your preferred PHP version here
          extensions: mbstring, intl, bcmath # You can add other extensions if required
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip git apache2

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"
        #continue-on-error: false   # This will cause the step to fail if Composer installation fails

      - name: Install dependencies using Composer
        run: |
          # Install dependencies (will skip if already installed)
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Display Installed Dependencies
        run: |
          echo "Installed Composer dependencies:"
          composer show
